/**
 * QuizPage - top-level quiz interface (practice + exam modes).
 *
 * A4c: `handleStart` is async and gated behind the existing `isLoading`
 * state — it prefers due-aware session selection (`selectSessionQuestions`,
 * backed by the SM-2 study store) and falls back to the plain
 * shuffle/slice selection internally if the store is unavailable or
 * throws, so quiz start can never hang.
 */

import { useRef, useState, useEffect } from 'react';
import { QuizSetup, Quiz, Exam } from './index';
import type { Question, QuizConfig, Category, LearnEntry } from '../../lib/quiz';
import {
  generateQuestions,
  getQuestionStats,
  selectSessionQuestions,
  getStudyStore,
  DEFAULT_STUDY_SETTINGS,
} from '../../lib/quiz';
import { STORAGE_KEYS } from '../../hooks/useLocalStorage';
import { Card, CardContent } from '../ui/Card';
import { Button } from '../ui/Button';

interface QuizPageProps {
  /** Learn content entries for generating questions */
  learnEntries: LearnEntry[];
  /** Curated, expert-vetted question bank entries (already mapped to Question). Curated-first. */
  curatedQuestions?: Question[];
}

export function QuizPage({ learnEntries, curatedQuestions = [] }: QuizPageProps) {
  const [allQuestions, setAllQuestions] = useState<Question[]>([]);
  const [selectedQuestions, setSelectedQuestions] = useState<Question[]>([]);
  const [config, setConfig] = useState<QuizConfig | null>(null);
  const [timeLimit, setTimeLimit] = useState<number>(30 * 60);
  const [isLoading, setIsLoading] = useState(true);
  const store = useRef(getStudyStore()).current;

  useEffect(() => {
    const autoGenerated = generateQuestions(learnEntries);
    // Curated-first: the pool order matters for selection (fresh/new items
    // are preferred in pool order), so the vetted bank leads.
    const curatedIds = new Set(curatedQuestions.map(q => q.id));
    const merged = [
      ...curatedQuestions,
      ...autoGenerated.filter(q => !curatedIds.has(q.id)),
    ];
    setAllQuestions(merged);
    setIsLoading(false);
  }, [learnEntries, curatedQuestions]);

  const stats = getQuestionStats(allQuestions);
  const availableQuestions = stats.byCategory as Record<Category, number>;

  const handleStart = async (newConfig: QuizConfig, examTimeLimit?: number) => {
    setIsLoading(true);
    try {
      let settings = DEFAULT_STUDY_SETTINGS;
      try {
        settings = await store.getSettings();
      } catch (err) {
        console.warn('[QuizPage] getSettings failed, using defaults:', err);
      }

      // selectSessionQuestions never throws — it falls back to the plain
      // shuffle().slice() selection internally on any store failure, so
      // quiz start can never hang here.
      const questions = await selectSessionQuestions(allQuestions, newConfig, store, settings);
      // An explicit Start is always a fresh session: discard any persisted
      // in-progress/completed state so useQuiz/useExam never resurrect a
      // stale session into the newly chosen configuration.
      if (typeof window !== 'undefined') {
        window.localStorage.removeItem(STORAGE_KEYS.QUIZ_STATE);
        window.localStorage.removeItem(STORAGE_KEYS.EXAM_STATE);
      }
      setSelectedQuestions(questions);
      setConfig(newConfig);
      if (examTimeLimit) {
        setTimeLimit(examTimeLimit);
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleBack = () => {
    setConfig(null);
    setSelectedQuestions([]);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white py-12">
      <div className="max-w-4xl mx-auto px-4">
        <div className="mb-8">
          <h2 className="text-2xl font-semibold text-slate-900">Practice and Exam Mode</h2>
          <p className="text-slate-600 mt-2">
            756 questions across all FGA subject areas. Practise at your own pace, or sit a timed mock exam.
          </p>
        </div>

        {isLoading ? (
          <div className="text-center py-12">
            <div className="animate-pulse text-slate-400">Loading questions...</div>
          </div>
        ) : config && selectedQuestions.length > 0 ? (
          config.mode === 'exam' ? (
            <Exam
              config={config}
              questions={selectedQuestions}
              timeLimit={timeLimit}
              onBack={handleBack}
            />
          ) : (
            <Quiz
              config={config}
              questions={selectedQuestions}
              onBack={handleBack}
            />
          )
        ) : (
          <>
            <Card className="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <CardContent className="p-0">
                <h3 className="text-base font-semibold text-slate-900">Challenge Tracks</h3>
                <p className="text-sm text-slate-600 mt-1">
                  Themed challenge tracks — structured study with staged mastery.
                </p>
              </CardContent>
              <Button
                variant="secondary"
                onClick={() => {
                  window.location.href = '/study/challenges';
                }}
              >
                Explore tracks
              </Button>
            </Card>
            <QuizSetup
              availableQuestions={availableQuestions}
              onStart={handleStart}
              showExamMode={true}
            />
          </>
        )}
      </div>
    </div>
  );
}
