/**
 * Build-time llms.txt endpoint (P2-11 + SEO v2 WB2).
 *
 * Surfaces the canonical content surfaces for LLM crawlers and AI search
 * indexers. We list every learn article, every tool category, and every
 * mineral page from the build-time database rather than scraping the sitemap,
 * because the sitemap is generated by `@astrojs/sitemap` at the same build
 * pass and isn't inspectable from inside an endpoint.
 *
 * Conforms to https://llmstxt.org/.
 */
import type { APIContext } from 'astro';
import { getCollection } from 'astro:content';
import {
  getAllMinerals,
  getAllFamilies,
  getPrimaryExpressionId,
  type MineralFamily,
} from '../lib/db-server';

const SITE = 'https://gemmology.dev';

interface ToolEntry {
  slug: string;
  title: string;
  description: string;
}

const TOOLS: ToolEntry[] = [
  {
    slug: 'measurement',
    title: 'Measurement',
    description:
      'Specific gravity (hydrostatic + water-temp corrected), refractometer lookup, birefringence, critical angle, carat estimator (with girdle correction), Hanneman/Hodgkinson over-the-limit RI.',
  },
  {
    slug: 'optical',
    title: 'Optical',
    description:
      'Dichroscope results, polariscope guide, refractometer simulator (with OTL behaviour), pleochroism reasoner, optic sign / 2V reasoner.',
  },
  {
    slug: 'lab',
    title: 'Lab',
    description:
      'Spectroscope calculator and reverse band-matcher against a 16-species absorption-band table, UV fluorescence lookup (LWUV/SWUV/phosphorescence).',
  },
  {
    slug: 'identification',
    title: 'Identification',
    description:
      'Filtered gemstone identifier — narrow against species using RI, SG, birefringence, hardness, dispersion, optical character.',
  },
  {
    slug: 'advanced',
    title: 'Advanced',
    description:
      'Evidence-weighted treatment-detection wizard (18 clues x 11 treatments), treatment reference table, proportion analyzer with GIA cut-grade overlay for round brilliants.',
  },
  {
    slug: 'conversions',
    title: 'Conversions',
    description:
      'Carat/gram/milligram weight converter, length and temperature converters used in gemmological measurement workflows.',
  },
];

function mineralLine(fam: MineralFamily): string {
  const bits: string[] = [];
  if (fam.crystal_system) bits.push(fam.crystal_system);
  if (fam.hardness_min != null && fam.hardness_max != null) {
    bits.push(
      fam.hardness_min === fam.hardness_max
        ? `H ${fam.hardness_min}`
        : `H ${fam.hardness_min}-${fam.hardness_max}`,
    );
  }
  if (fam.ri_min != null && fam.ri_max != null) {
    bits.push(
      fam.ri_min === fam.ri_max
        ? `RI ${fam.ri_min}`
        : `RI ${fam.ri_min}-${fam.ri_max}`,
    );
  }
  if (fam.sg_min != null && fam.sg_max != null) {
    bits.push(
      fam.sg_min === fam.sg_max
        ? `SG ${fam.sg_min}`
        : `SG ${fam.sg_min}-${fam.sg_max}`,
    );
  }
  if (fam.origin && fam.origin !== 'natural') bits.push(fam.origin);
  const tail = bits.length > 0 ? `${bits.join(', ')}.` : '';
  const desc = fam.description?.trim();
  const summary = desc ? `${tail} ${desc}` : tail || fam.name;
  return `- [${fam.name}](${SITE}/minerals/${fam.id}): ${summary}`.trim();
}

export async function GET(_ctx: APIContext): Promise<Response> {
  const learnEntries = await getCollection('learn');
  const minerals = await getAllMinerals();
  const families = await getAllFamilies();

  // Build a unique mineral URL set the same way [slug].astro does:
  // expression-level pages plus a family-level page that resolves to its
  // primary expression. Dedup by URL.
  const mineralUrls = new Set<string>();
  for (const m of minerals) mineralUrls.add(`${SITE}/minerals/${m.id}`);
  for (const fam of families) {
    if (!mineralUrls.has(`${SITE}/minerals/${fam.id}`)) {
      const primary = await getPrimaryExpressionId(fam.id);
      if (primary) mineralUrls.add(`${SITE}/minerals/${fam.id}`);
    }
  }

  const lines: string[] = [];
  lines.push('# gemmology.dev');
  lines.push('');
  lines.push(
    '> Open, FGA-aligned reference and study toolkit for coloured gemstones. Free and open-source. Reference data covers 121 mineral families (natural, synthetic, simulant, composite) and 171 crystal expressions; the curriculum is structured around the Fellowship of the Gemmological Association (FGA) Diploma syllabus.',
  );
  lines.push('');
  lines.push('## Core surfaces');
  lines.push(
    `- [Home](${SITE}/): Project overview, mineral counts, calculator entry points.`,
  );
  lines.push(
    `- [Mineral gallery](${SITE}/gallery/): Browse all ${mineralUrls.size} mineral pages with crystal SVGs rendered from Miller indices.`,
  );
  lines.push(
    `- [Learn hub](${SITE}/learn/): ${learnEntries.length} curriculum-aligned articles across 8 categories (fundamentals, equipment, species, identification, phenomena, origin, market, care).`,
  );
  lines.push(
    `- [Quiz & exam](${SITE}/quiz/): Spaced-repetition practice and timed FGA-style exam mode covering the same 8 categories.`,
  );
  lines.push(
    `- [Tools hub](${SITE}/tools/): Six categories of gemmological calculators and reasoners — measurement, optical, lab, identification, advanced, conversions.`,
  );
  lines.push(
    `- [CDL specification](${SITE}/docs/cdl/): Crystal Description Language v2 reference (the notation used for all crystal morphology data).`,
  );
  lines.push(
    `- [API reference](${SITE}/docs/api/cdl-parser/): Python package APIs for cdl-parser, crystal-geometry, mineral-database, crystal-renderer, cdl-lsp.`,
  );
  lines.push(
    `- [About](${SITE}/about/): Editorial standards, sourcing, contributor information.`,
  );
  lines.push('');

  // Tools — listed individually so AI crawlers can resolve "what calculators
  // does gemmology.dev have" without rendering the React islands.
  lines.push('## Tools');
  lines.push('');
  lines.push(`- [Tools hub](${SITE}/tools/): Index of all six tool categories.`);
  for (const t of TOOLS) {
    lines.push(`- [${t.title}](${SITE}/tools/${t.slug}/): ${t.description}`);
  }
  lines.push('');

  // Group learn entries by category for readability.
  const byCat = new Map<string, typeof learnEntries>();
  for (const e of learnEntries) {
    const cat = e.data.category;
    if (!byCat.has(cat)) byCat.set(cat, [] as typeof learnEntries);
    byCat.get(cat)!.push(e);
  }
  const catOrder = [
    'fundamentals',
    'equipment',
    'species',
    'identification',
    'phenomena',
    'origin',
    'market',
    'care',
  ];
  lines.push('## Learn');
  lines.push('');
  for (const cat of catOrder) {
    const entries = byCat.get(cat);
    if (!entries || entries.length === 0) continue;
    lines.push(`### ${cat.charAt(0).toUpperCase() + cat.slice(1)}`);
    for (const entry of entries.sort((a, b) => a.data.order - b.data.order)) {
      lines.push(
        `- [${entry.data.title}](${SITE}/learn/${entry.id}): ${entry.data.description}`,
      );
    }
    lines.push('');
  }

  lines.push('## Minerals');
  lines.push('');
  lines.push(
    'Each entry summarises crystal system, hardness range, RI range, SG range, origin classification, and a short reference description.',
  );
  lines.push('');
  const familyById = new Map(families.map((f) => [`${SITE}/minerals/${f.id}`, f]));
  for (const url of [...mineralUrls].sort()) {
    const fam = familyById.get(url);
    if (fam) {
      lines.push(mineralLine(fam));
    } else {
      // Expression-level slug without a matching family (rare): fall back.
      const slug = url.replace(`${SITE}/minerals/`, '');
      lines.push(`- [${slug}](${url})`);
    }
  }
  lines.push('');

  lines.push('## Licensing (training use)');
  lines.push('');
  lines.push(
    '- Code (TypeScript, Python packages, build pipeline) is licensed under MIT.',
  );
  lines.push(
    '- Educational content (`/learn/` articles and the upstream `gemmology-knowledge` curriculum) is licensed under CC BY-SA 4.0.',
  );
  lines.push(
    '- AI training and AI-search use of this content is permitted under those licences, subject to attribution to gemmology.dev and ShareAlike for derivative works of the educational content.',
  );
  lines.push(
    '- The mineral reference data is compiled from peer-reviewed gemmological sources; numerical ranges are verified across multiple sources before inclusion. See [About](https://gemmology.dev/about/) for editorial standards.',
  );
  lines.push('');

  lines.push('## Source');
  lines.push('- https://github.com/gemmology-dev');
  lines.push(
    '- Corrections via GitHub issues at https://github.com/gemmology-dev/gemmology.dev/issues',
  );

  return new Response(lines.join('\n'), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Match the minerals.db cache policy — the file is rebuilt every deploy.
      'Cache-Control': 'public, max-age=3600, must-revalidate',
    },
  });
}
