/**
 * Build-time llms.txt endpoint (P2-11).
 *
 * Surfaces the canonical content surfaces for LLM crawlers and AI search
 * indexers. We list every learn article and every mineral page from the
 * collected/built site rather than scraping the sitemap, because the sitemap
 * is generated by `@astrojs/sitemap` at the same build pass and isn't
 * inspectable from inside an endpoint.
 */
import type { APIContext } from 'astro';
import { getCollection } from 'astro:content';
import { getAllMinerals, getAllFamilies, getPrimaryExpressionId } from '../lib/db-server';

const SITE = 'https://gemmology.dev';

export async function GET(_ctx: APIContext): Promise<Response> {
  const learnEntries = await getCollection('learn');
  const minerals = await getAllMinerals();
  const families = await getAllFamilies();

  // Build a unique mineral URL set the same way [slug].astro does:
  // expression-level pages plus a family-level page that resolves to its
  // primary expression. Dedup by URL.
  const mineralUrls = new Set<string>();
  for (const m of minerals) mineralUrls.add(`${SITE}/minerals/${m.id}`);
  for (const fam of families) {
    if (!mineralUrls.has(`${SITE}/minerals/${fam.id}`)) {
      const primary = await getPrimaryExpressionId(fam.id);
      if (primary) mineralUrls.add(`${SITE}/minerals/${fam.id}`);
    }
  }

  const lines: string[] = [];
  lines.push('# gemmology.dev');
  lines.push('');
  lines.push('> Open, FGA-aligned reference and study toolkit for coloured gemstones. Free and open-source.');
  lines.push('');
  lines.push('## Core surfaces');
  lines.push(`- [Home](${SITE}/): Project overview, mineral counts, calculators.`);
  lines.push(`- [Mineral gallery](${SITE}/gallery/): Browse all ${mineralUrls.size} mineral pages with crystal SVGs.`);
  lines.push(`- [Learn hub](${SITE}/learn/): ${learnEntries.length} curriculum-aligned articles across crystallography, optics, identification, and species.`);
  lines.push(`- [CDL specification](${SITE}/docs/cdl/): Crystal Description Language v2 reference.`);
  lines.push(`- [API reference](${SITE}/docs/api/cdl-parser/): Python package APIs.`);
  lines.push(`- [About](${SITE}/about/): Editorial standards, sourcing, licensing.`);
  lines.push('');

  // Group learn entries by category for readability.
  const byCat = new Map<string, typeof learnEntries>();
  for (const e of learnEntries) {
    const cat = e.data.category;
    if (!byCat.has(cat)) byCat.set(cat, [] as typeof learnEntries);
    byCat.get(cat)!.push(e);
  }
  const catOrder = ['fundamentals', 'equipment', 'species', 'identification', 'phenomena', 'origin', 'market', 'care'];
  lines.push('## Learn');
  lines.push('');
  for (const cat of catOrder) {
    const entries = byCat.get(cat);
    if (!entries || entries.length === 0) continue;
    lines.push(`### ${cat.charAt(0).toUpperCase() + cat.slice(1)}`);
    for (const entry of entries.sort((a, b) => a.data.order - b.data.order)) {
      lines.push(`- [${entry.data.title}](${SITE}/learn/${entry.id}): ${entry.data.description}`);
    }
    lines.push('');
  }

  lines.push('## Minerals');
  lines.push('');
  for (const url of [...mineralUrls].sort()) {
    lines.push(`- ${url}`);
  }
  lines.push('');
  lines.push('## Licensing');
  lines.push('- Code: MIT');
  lines.push('- Educational content: CC BY-SA 4.0');
  lines.push('');
  lines.push('## Source');
  lines.push('- https://github.com/gemmology-dev');

  return new Response(lines.join('\n'), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Match the minerals.db cache policy — the file is rebuilt every deploy.
      'Cache-Control': 'public, max-age=3600, must-revalidate',
    },
  });
}
